# -*- coding: utf-8 -*-
"""Regressão.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pi4Yl2UfXVxuX8s6ptokaXKIo8bEfc6h
"""

# Install dependencies as needed:
# pip install kagglehub[pandas-datasets]
import kagglehub
from kagglehub import KaggleDatasetAdapter

# Set the path to the file you'd like to load
file_path = "insurance.csv"

# Load the latest version
df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "mirichoi0218/insurance",
  file_path,
  # Provide any additional arguments like
  # sql_query or pandas_kwargs. See the
  # documenation for more information:
  # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
)

df.shape

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Visualizando informações básicas e valores nulos
print("--- Informações do Dataset ---")
print(df.info())
print("\n--- Valores Nulos ---")
print(df.isnull().sum())

# Configurando o estilo dos gráficos
sns.set_theme(style="whitegrid")

# 1. Distribuição da variável alvo (charges)
plt.figure(figsize=(10, 5))
sns.histplot(df['charges'], bins=50, kde=True, color='blue')
plt.title('Distribuição dos Custos Médicos (charges)')
plt.xlabel('Custos')
plt.ylabel('Frequência')
plt.show()

# 2. Impacto de ser fumante nos custos
plt.figure(figsize=(8, 5))
sns.boxplot(x='smoker', y='charges', data=df, palette='Set2')
plt.title('Custos Médicos: Fumantes vs Não Fumantes')
plt.show()

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# 1. Encoding de variáveis categóricas (One-Hot Encoding)
# Transforma as colunas de texto em colunas binárias (0 ou 1)
df_encoded = pd.get_dummies(df, columns=['sex', 'smoker', 'region'], drop_first=True)

# 2. Separação entre variáveis independentes (X) e a variável alvo (y)
X = df_encoded.drop('charges', axis=1)
y = df_encoded['charges']

# 3. Divisão em Treino (80%) e Teste (20%)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 4. Escalonamento (Padronização)
# Isso é crucial para o SVM e Redes Neurais (MLP) funcionarem bem
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print(f"Tamanho do treino: {X_train_scaled.shape}")
print(f"Tamanho do teste: {X_test_scaled.shape}")

from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from sklearn.svm import SVR
from sklearn.neural_network import MLPRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Inicializando os 6 modelos exigidos
modelos = {
    "Linear Regression": LinearRegression(),
    "Decision Tree": DecisionTreeRegressor(random_state=42),
    "Random Forest": RandomForestRegressor(
      n_estimators=300,
      max_depth=10,
      min_samples_split=5,
      min_samples_leaf=2,
      random_state=42
    ),
   "XGBoost": XGBRegressor(
      n_estimators=300,
      learning_rate=0.05,
      max_depth=4,
      subsample=0.8,
      colsample_bytree=0.8,
      random_state=42
    ),
    "SVR": SVR(kernel='linear'), # Usando linear ou rbf, dependendo do teste
    "MLP Regressor": MLPRegressor(
    hidden_layer_sizes=(128, 64),
    activation='relu',
    solver='adam',
    learning_rate='adaptive',
    max_iter=3000,
    early_stopping=True,
    random_state=42
    )
}

# Lista para armazenar os resultados
resultados = []

# Loop para treinar e avaliar cada modelo
for nome, modelo in modelos.items():
    # Treinamento (fit)
    modelo.fit(X_train_scaled, y_train)

    # Previsão (predict)
    y_pred = modelo.predict(X_test_scaled)

    # Cálculo das métricas
    mae = mean_absolute_error(y_test, y_pred)
    mse = mean_squared_error(y_test, y_pred)
    rmse = np.sqrt(mse) # RMSE é a raiz do MSE
    r2 = r2_score(y_test, y_pred)

    # Adicionando na lista de resultados
    resultados.append({
        "Modelo": nome,
        "MAE": round(mae, 2),
        "MSE": round(mse, 2),
        "RMSE": round(rmse, 2),
        "R²": round(r2, 4)
    })

# Convertendo para um DataFrame do Pandas para visualizar como tabela
df_resultados = pd.DataFrame(resultados)

# Ordenando a tabela pelo melhor R² (mais próximo de 1)
df_resultados = df_resultados.sort_values(by="R²", ascending=False).reset_index(drop=True)

# Ordenando pelos melhores resultados
df_resultados = df_resultados.sort_values(
    by='R²',
    ascending=False
).reset_index(drop=True)

print("\n--- Resultados dos Modelos de Regressão ---")

display(df_resultados)

import matplotlib.pyplot as plt
from sklearn.metrics import r2_score

# Criando uma figura com 2 linhas e 3 colunas de gráficos
fig, axes = plt.subplots(2, 3, figsize=(18, 10))
axes = axes.flatten() # Achata a matriz de eixos para facilitar o loop

# Loop para gerar um gráfico para cada modelo
for i, (nome, modelo) in enumerate(modelos.items()):
    # Usando o modelo já treinado para prever os dados de teste
    y_pred = modelo.predict(X_test_scaled)

    # Plotando os pontos (Valores Reais no eixo X, Preditos no eixo Y)
    axes[i].scatter(y_test, y_pred, alpha=0.5, color='royalblue')

    # Criando a linha vermelha tracejada de "Predição Perfeita" (y = x)
    min_val = min(y_test.min(), y_pred.min())
    max_val = max(y_test.max(), y_pred.max())
    axes[i].plot([min_val, max_val], [min_val, max_val], color='red', linestyle='--')

    # Ajustando títulos e rótulos
    # Puxamos o R² da tabela ou recalculamos rapidamente para por no título
    r2 = r2_score(y_test, y_pred)
    axes[i].set_title(f'{nome} ($R^2$: {r2:.4f})', fontsize=12, fontweight='bold')
    axes[i].set_xlabel('Valores Reais (Custos)')
    axes[i].set_ylabel('Valores Preditos')

# Ajusta o espaçamento entre os gráficos para não sobrepor os textos
plt.tight_layout()
plt.show()

"""# parte não supervisionada - PCA"""

from sklearn.decomposition import PCA

# Para agrupamento, vamos padronizar o dataset X inteiro
X_scaled_full = scaler.fit_transform(X)

# 1. Aplicando PCA para reduzir a 2 componentes (para visualização 2D)
pca = PCA(n_components=2, random_state=42)
X_pca = pca.fit_transform(X_scaled_full)

# 2. Variância Explicada
variancia = pca.explained_variance_ratio_
print(f"Variância explicada pelo Componente 1: {variancia[0]*100:.2f}%")
print(f"Variância explicada pelo Componente 2: {variancia[1]*100:.2f}%")
print(f"Variância Total Explicada (2D): {sum(variancia)*100:.2f}%\n")

# 3. Visualização 2D do PCA
plt.figure(figsize=(8, 6))
# Podemos usar o y (charges) apenas para colorir e ver se formam grupos naturais
scatter = plt.scatter(X_pca[:, 0], X_pca[:, 1], c=y, cmap='viridis', alpha=0.6)
plt.colorbar(scatter, label='Custos (charges)')
plt.title('PCA: Visualização 2D dos Dados de Seguro')
plt.xlabel('Componente Principal 1')
plt.ylabel('Componente Principal 2')
plt.show()

"""## Análise PCA

O PCA (Principal Component Analysis) foi utilizado para reduzir a dimensionalidade
do dataset, permitindo visualizar os dados em duas dimensões.

As duas componentes principais concentram a maior parte da variabilidade
presente no conjunto de dados.

A visualização mostra como os dados estão distribuídos no espaço reduzido,
permitindo identificar possíveis agrupamentos e padrões naturais.

# parte não supervisionada - kmeans
"""

from sklearn.cluster import KMeans
from sklearn.metrics import (
    silhouette_score,
    calinski_harabasz_score,
    davies_bouldin_score
)

inercia = []
silhouette_scores = []

K_range = range(2, 11)

for k in K_range:

    kmeans = KMeans(
        n_clusters=k,
        random_state=42,
        n_init=10
    )

    kmeans.fit(X_scaled_full)

    # Inércia
    inercia.append(kmeans.inertia_)

    # Silhouette Score
    silhouette_scores.append(
        silhouette_score(
            X_scaled_full,
            kmeans.labels_
        )
    )

fig, ax1 = plt.subplots(figsize=(11,6))

# Inércia
color = 'tab:blue'

ax1.set_xlabel('Número de Clusters (K)', fontsize=12)

ax1.set_ylabel(
    'Inércia',
    color=color,
    fontsize=12
)

ax1.plot(
    K_range,
    inercia,
    marker='o',
    color=color,
    linewidth=2
)

ax1.tick_params(
    axis='y',
    labelcolor=color
)

# Silhouette
ax2 = ax1.twinx()

color = 'tab:red'

ax2.set_ylabel(
    'Silhouette Score',
    color=color,
    fontsize=12
)

ax2.plot(
    K_range,
    silhouette_scores,
    marker='s',
    linestyle='dashed',
    color=color,
    linewidth=2
)

ax2.tick_params(
    axis='y',
    labelcolor=color
)

plt.title(
    'K-Means - Método do Cotovelo e Silhouette Score',
    fontsize=14
)

plt.grid(alpha=0.3)

plt.show()

# Escolhendo K=3 (ajuste se necessário)
kmeans_final = KMeans(
    n_clusters=3,
    random_state=42,
    n_init=10
)

labels_kmeans = kmeans_final.fit_predict(X_scaled_full)

silhouette_kmeans = silhouette_score(
    X_scaled_full,
    labels_kmeans
)

ch_kmeans = calinski_harabasz_score(
    X_scaled_full,
    labels_kmeans
)

db_kmeans = davies_bouldin_score(
    X_scaled_full,
    labels_kmeans
)

print("\n=== Métricas K-Means ===\n")
print(f"Silhouette Score: {silhouette_kmeans:.4f}")
print(f"Calinski-Harabasz: {ch_kmeans:.2f}")
print(f"Davies-Bouldin: {db_kmeans:.4f}")

# =========================================================
# Visualização dos Clusters com PCA
# =========================================================

plt.figure(figsize=(10,7))

plt.scatter(
    X_pca[:,0],
    X_pca[:,1],
    c=labels_kmeans,
    cmap='viridis',
    alpha=0.7
)

plt.xlabel(
    'Componente Principal 1',
    fontsize=12
)

plt.ylabel(
    'Componente Principal 2',
    fontsize=12
)

plt.title(
    'K-Means - Visualização dos Clusters',
    fontsize=14
)

plt.grid(alpha=0.3)

plt.show()

"""## Análise K-Means

O algoritmo K-Means foi utilizado para identificar agrupamentos
naturais no dataset.

O Método do Cotovelo foi utilizado para auxiliar na escolha do número
ideal de clusters, enquanto o Silhouette Score ajudou a avaliar
a qualidade da separação entre os grupos.

As métricas de clusterização indicam o nível de compactação e separação
dos clusters encontrados.

parte não supervisionada - DBSCAN
"""

from sklearn.cluster import DBSCAN
from sklearn.metrics import (
    silhouette_score,
    calinski_harabasz_score,
    davies_bouldin_score
)

# =========================================================
# K-Means - Comparação de Clusters
# =========================================================

kmeans_2 = KMeans(
    n_clusters=2,
    random_state=42,
    n_init=10
).fit(X_scaled_full)

kmeans_3 = KMeans(
    n_clusters=3,
    random_state=42,
    n_init=10
).fit(X_scaled_full)

# =========================================================
# DBSCAN
# =========================================================

dbscan = DBSCAN(
    eps=1.5,
    min_samples=5
).fit(X_scaled_full)

# =========================================================
# Função para calcular métricas
# =========================================================

def calcular_metricas(modelo, dados, nome, is_kmeans=True):

    labels = modelo.labels_

    # Quantidade de clusters válidos
    n_clusters = len(set(labels)) - (
        1 if -1 in labels else 0
    )

    # Caso encontre poucos clusters
    if n_clusters < 2:

        return {
            "Método": nome,
            "Clusters": n_clusters,
            "Inércia": "-",
            "Silhouette": "-",
            "Calinski-Harabasz": "-",
            "Davies-Bouldin": "-"
        }

    # Inércia apenas para K-Means
    inercia = (
        round(modelo.inertia_, 2)
        if is_kmeans else "-"
    )

    sil = round(
        silhouette_score(dados, labels),
        4
    )

    ch = round(
        calinski_harabasz_score(dados, labels),
        2
    )

    db = round(
        davies_bouldin_score(dados, labels),
        4
    )

    return {
        "Método": nome,
        "Clusters": n_clusters,
        "Inércia": inercia,
        "Silhouette": sil,
        "Calinski-Harabasz": ch,
        "Davies-Bouldin": db
    }

# =========================================================
# Resultados
# =========================================================

resultados_cluster = [

    calcular_metricas(
        kmeans_2,
        X_scaled_full,
        "K-Means (K=2)"
    ),

    calcular_metricas(
        kmeans_3,
        X_scaled_full,
        "K-Means (K=3)"
    ),

    calcular_metricas(
        dbscan,
        X_scaled_full,
        "DBSCAN",
        is_kmeans=False
    )
]

# =========================================================
# DataFrame Final
# =========================================================

df_cluster = pd.DataFrame(resultados_cluster)

print("\n=== Resultados das Métricas de Agrupamento ===\n")

display(df_cluster)

# =========================================================
# Visualização DBSCAN com PCA
# =========================================================

plt.figure(figsize=(10,7))

plt.scatter(
    X_pca[:,0],
    X_pca[:,1],
    c=dbscan.labels_,
    cmap='plasma',
    alpha=0.7
)

plt.xlabel(
    'Componente Principal 1',
    fontsize=12
)

plt.ylabel(
    'Componente Principal 2',
    fontsize=12
)

plt.title(
    'DBSCAN - Visualização dos Clusters',
    fontsize=14
)

plt.grid(alpha=0.3)

plt.show()

"""## Análise DBSCAN

O DBSCAN foi utilizado como método de agrupamento baseado em densidade.

Diferente do K-Means, o DBSCAN não exige a definição prévia do número
de clusters e possui capacidade de identificar ruídos e outliers.

As métricas obtidas permitem comparar a qualidade dos agrupamentos
entre os diferentes métodos utilizados.
"""